### ISSUE TITLE
error: https://docs.github.com/v3/search/ ; and we need wait 20s

### ISSUE THREAD

**Issue by omarhashem123** [damit5/gitdorks_go#1]
while running the tool i get this error
error: https://docs.github.com/v3/search/ ; and we need wait 20s

**Comment by damit5** [comment]
Could you provide the directory tree and run parameters? let me try to reproduce this.

**Comment by dilatedpupils** [comment]
Hello, same problem here:
the whole command is:
gitdorks_go -gd ./Dorks/smalldorks.txt -nws 20 -target shipt.com -tf token.txt -ew 3

What I get:

[+] got 1 tokens and 30 dorks

shipt.com "token"  |  (72)  |  https://github.com/search?q=shipt.com+%22token%22&s=indexed&type=Code&o=desc
shipt.com "password"  |  (93)  |  https://github.com/search?q=shipt.com+%22password%22&s=indexed&type=Code&o=desc
error: https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits ; and we need wait 20s

**Comment by damit5** [comment]
> 

error "secondary rate limits" belongs to normal phenomenon, as shown below

![normal](https://github.com/damit5/gitdorks_go/raw/d4m1ts/README.assets/image-20220316155344201.png)
