### ISSUE TITLE
大佬为什么不考虑采用go-github库

### ISSUE THREAD

**Issue by Mia0a-hi** [damit5/gitdorks_go#2]
大佬为什么不考虑采用go-github库

**Comment by damit5** [comment]
官方提供了好用的API，我也只用一个查询接口，没必要为了这点小事引入一个全面的库；而且自己写定制化更高，有什么bug一下就知道是哪里的问题，方便修改调试。

后面如果要扩充其他的功能，会考虑的，谢谢师傅提醒

希望这个回答可以解决您的疑问哈哈
